; AI Careon — PlatformIO Configuration
; ──────────────────────────────────────
; Board:     Espressif ESP32 Dev Module
; Framework: Arduino

[env:esp32dev]
platform  = espressif32
board     = esp32dev
framework = arduino

monitor_speed   = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
    adafruit/DHT sensor library
    adafruit/Adafruit Unified Sensor
    electroniccats/MPU6050
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library
    bogde/HX711
    mobizt/Firebase ESP32 Client
    blynkkk/Blynk
    bblanchon/ArduinoJson
